name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install and Build
      run: |
        npm install
        npm run build
    
    - name: Commit dist folder
      run: |
        git add dist -f
        git config --local user.name "actions-user"
        git config --local user.email "action@github.com"
        git commit -m "Build dist folder" || echo "No changes to commit"
    
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
